services:
  customer-db:
    image: postgres:15
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: customer_db
    ports:
      - "5433:5433"
    volumes:
      - customer_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf


  customer-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customer-api
    restart: always
    depends_on:
      - customer-db
    environment:
      DB_HOST: customer-db
      DB_PORT: 5433
      DB_NAME: customer_db
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8082:8082"

volumes:
  customer_data: